### ISSUE TITLE
Support for modern Unity versions (2019-2021)

### ISSUE THREAD

**Issue by o2co2** [thinksquirrel/fluviofx#29]
Packages\com.thinksquirrel.fluviofx\Editor\ShaderPostprocessor\ShaderPostprocessor.cs(72,52): error CS0122: 'VFXDataParticle.capacity' is inaccessible due to its protection level

Hope to get help

**Comment by lmontoute** [comment]
2019.3 support isn't here yet, and probably won't land until it releases. For now you'll want to use 2019.2. Sorry!

**Comment by Onat-H** [comment]
Hi, are there  any updates regarding 2019.3 support? Love your work!!

**Comment by TashaSkyUp** [comment]
Would also love 2019.3 support.. willing to help if you can point me the right direction?

**Comment by AC0793** [comment]
I am also eagerly looking forward to 2019.3 support. Are there any updates or progress on that? Thanks!

**Comment by lmontoute** [comment]
I'll try to get on it this weekend. Thanks for the patience folks!

**Comment by s-t-a-a-l-e** [comment]
The first thing I do in the morning is to check the FluvioFX project status. I hope you will be able to  get it working in 2019.3 (or 2020.1.x) soon. It stopped working in the latest 2019.2 version I use, so that solution is kind of stranded. Thanks!

**Comment by lmontoute** [comment]
Unfortunately I hit a snag and have had a few full weekends lately. This week is finally looking to open up for me, though!

**Comment by lmontoute** [comment]
Update on this...I've started a bit on an update, but then _everything_ got shifted around at work and home due to well, everything going on right now. So I'm playing it by ear for now. Sorry that this keeps getting delayed!

**Comment by enginarer** [comment]
Hi, any update on this? Cheers!

**Comment by AC0793** [comment]
Hello, I am also interested in any updates or progress on this. Thanks!

**Comment by lmontoute** [comment]
So sorry for the delay! Still very busy at work here due to COVID, so no ETA at the moment! If anyone would like to help take on this task, let me know and I'd be happy to help point you in the right direction!

**Comment by landonth** [comment]
@lmontoute I'm willing and able to assist on this. I've already been working on some VFX graph extensions of my own and would benefit from FluvioFX functioning on more recent versions.

**Comment by AC0793** [comment]
@landonth @lmontoute Hello, any progress on this so far? I'm not sure how much I can help yet, but i'm interested in assisting as well.

**Comment by ahmed3DMindd** [comment]
Library\PackageCache\com.fluvio.fx@a3f3d0ea2f\Editor\ShaderPostprocessor\ShaderPostprocessor.cs(72,52): error CS0122: 'VFXDataParticle.capacity' is inaccessible due to its protection level

**Comment by landonth** [comment]
@lmontoute Good news! I have made a major breakthrough in the update effort. FluvioFX C# is compiling without error and compiling HLSL compute shaders without error. The only issue that remains is there seems to be an issue with inter-particle forces that I am guessing is related to read or writing bucket or neighbor data. I haven't really gotten into debugging this (hopefully final) issue blocking a worthy PR. but I'm hoping it's only something trivial like an index offset to the attribute byte address buffers. The starting addresses seem correct at a glance anyway, maybe something changed in the VFX graoh addressing scheme? who knows. More to come soon.

**Comment by lmontoute** [comment]
Heck yeah @landonth ! I greatly appreciate the effort on this.

**Comment by strangerattractor** [comment]
Whoop, so looking forward to 2019.3 support!

**Comment by landonth** [comment]
@strangerattractor @lmontoute at this point support seems likely for:
- Unity 2019.4 LTS + Visual Effect Graph 7.4 (I have yet to test but should be trivial)
- Unity 2020.1 (Beta, Official soon) + Visual Effect Graph 8.1 (The version I am working from)

**Comment by landonth** [comment]
@lmontoute 
Things are finicky but mostly working currently with some workarounds I am ironing out, but would of course be grateful for any assistance or guidance

1.  I am having to set Mass and Force attributes manually in their own Update context, but that should be taken care of by the Initialize solver block update context, I know what needs to be done just haven't tackled it yet.
2. There may not strictly be a neighbor search issue. I seem to have consistent problems with the default bucket count of 32. There are these plaid grid like divergence patterns that cause massive instability and it was driving me crazy because I couldn't find a culprit i just finally thought to change the bucket count constant. The issue looks similar to issues you'd see when a compute dispatch size is too small and some threads are just not executing, etc.. I am currently using bucket count of 64 and everything works great. Maybe something GPU hardware / driver specific? I don't know.

If you have any ideas or you want to take a look, let me know. I haven't pushed to public origin on my fork because I don't want a bunch of people trying to use this almost complete but not quite version and then opening up new issues or being confused that setting the attributes are all wacky and duplicated and confusing right now due to the workaround.... and idk about the plaid grid bucket size issue I want to test that on some other GPUs.

**Comment by lmontoute** [comment]
In the past that plaid pattern has happened with lower bucket counts due to particles that have too many neighbors (more than the bucket can hold). This caused some particles to be ignored in simulation/pop in and out every frame and created unstable "ripples" at the edges of grid cells.

In older versions of Fluvio (pre-FluvioFX) we actually increased the default bucket size due to this. Not sure if this is the same issue, but how many particles is your simulation at? Also how densely packed are they?

**Comment by strangerattractor** [comment]
Still holding my breath for this update :-) slowly turning blue now.
Any news?
I'd love to help, but working in the backend of VFX-Graph is clearly beyond me. I would probably be able to help with testing though. Lemme know if I can do anything.

**Comment by AC0793** [comment]
@strangerattractor Same here :-) 

Do you have any updates, @landonth @lmontoute ? Thanks again for all of your hard work so far!

**Comment by ShiftedClock** [comment]
@landonth Can you share the progress you've made? I'm interested in picking up from where you left off. If you can share any insights you had, I'd appreciate that.

I really want to experiment with Fluvio in 2020.1. Please let me know if you can share the progress you made, and any barriers you identified to finishing the upgrade. Thanks.

**Comment by landonth** [comment]
Hey all, currently working on a project deadline for GDC coming up and then i'll be able to put a PR together for my progress on this within the next few weeks. The status is currently the same as my last post, though I also noticed that upgrading Unity Editor seems to invalidate and then break any graphs and they have to be rebuilt that is to say, FluvioFX operators and blocks will disappear and need to be re-added. My plan already was to wait until Unity 2020.1 was out of beta and that just happened, so it's all coming together.

**Comment by lmontoute** [comment]
@landonth Thanks again for leading the charge on this! Let me know if you have any thoughts on the invalidation issues, it's happened with pretty much every Unity release and seriously hurts the ability for users to upgrade once they've integrated FluvioFX. Honestly that may need its own issue tracking.

**Comment by landonth** [comment]
@lmontoute I appreciate it and glad to be a contributor (very soon.) I will publish my fork online here and get some eyes on it to work out the major remaining issues before a PR. And actually glad to hear to invalidation issue was already known. Worst case scenario we live with it and push for the planned VFX graph APIs to make this whole thing easier.

**Comment by ShiftedClock** [comment]
I don't know how active the Unity Visual Effect team is in checking this board, but it might be useful to provide feedback or guidance to them on particular issues that would help Fluvio support: https://portal.productboard.com/unity/1-unity-graphics/tabs/9-visual-effect-graph

I've submitted details for why I need ComputeBuffer support in VFX Graph, for instance, which is in the "Next Up" category. If there are any specific features that would benefit Fluvio, perhaps details would help the VFX Graph team better support it in future versions of Unity.

Just a thought.

**Comment by lmontoute** [comment]
Thanks for the link! I've been in touch with the VFX Graph team at Unity about our needs, and while admittedly it's been a while, they're aware of some of the issues we've had to work around to make FluvioFX possible.

**Comment by lmontoute** [comment]
I might have 1-2 days to lend a helping hand with this over the weekend! @landonth if you're interested in sharing your work so far, I'd love to chat about it (here, in a PR, or directly are all fine - just let me know how best to get in touch)

**Comment by AC0793** [comment]
@lmontoute @landonth Awesome! I was just about to ask about this again. :-) I can help test this weekend as well.

**Comment by landonth** [comment]
@lmontoute @AC0793 I will be mostly afk this weekend but I will publish my fork tonight at least so you can take a look over the weekend?

**Comment by landonth** [comment]
https://github.com/fluviofx/fluviofx/compare/master...landonth:wip2020

**Comment by landonth** [comment]
@lmontoute https://github.com/fluviofx/fluviofx/compare/master...landonth:wip2020

**Comment by kirkokuev** [comment]
Hello, so I have tried following to make this work:
1. Cloned repository from github
2. Saved this file https://github.com/fluviofx/fluviofx/compare/master...landonth:wip2020 and applied as patch to downloaded repository
3. Installed Visual Effect Graph 8.1.0 through package manager
4. Installed patched fluviofx with "Add package from disk"
5. Receive "FluvioFX install successful!" in log

And then it won't work, in the end I am left with 230 compiler errors with following messages
`fluviofx-master\Editor\Blocks\Collision\CollisionCylinder.cs(9,53): error CS0122: 'CollisionCylinder' is inaccessible due to its protection level`
or 
`fluviofx-master\Editor\Blocks\Solver\FluvioFXBlock.cs(19,40): error CS0115: 'FluvioFXBlock.compatibleContexts': no suitable method found to override`

This goes for all the fluviofx scripts.

I am trying this on Unity 2020.2.0a17.2267. 
Do you have any suggestions for making this work?

**Comment by landonth** [comment]
@kirkokuev what i recommend is to try the versions of Unity & VFX graph i noted in my last post in this thread. also note the additional steps and known issues.

and feel free to try to get it working on other Unity versions, though the rule of thumb is to always use the VFX graph (or any official package) version that is verified / tested / bundled with that Unity version. e.g. 2020.2 + VFX graph 8.1 were never designed to work together. you'd need to use 2020.2 + VFX graph 10.x. you can determine what versions exactly by looking in the package manager or in the Unity packages documentation: https://docs.unity3d.com/2020.2/Documentation/Manual/pack-safe.html

if you are using an alpha release like this, you're gonna have an even harder time --expect a ton of errors due to breaking changes and bugs in alphas even without installing any 3rd party packages. don't really expect anything to work in alpha. 2020.2 is already in beta though and has a better chance of being somewhat stable.

**Comment by kirkokuev** [comment]
Thank you @landonth. I will try with exact version of Unity that you used. However it is strange that package manager only gives me VFX graph 8.1 and 8.2 and not 10.x versions.

**Comment by AC0793** [comment]
@landonth @lmontoute  So far I also got around 230 errors running Unity 2020.1 with VFX Graph 8.3.1, then I reinstalled FluvioFX and was left with just the one error that we're familiar with:  "D:\fluviofx-master\fluviofx-master\Editor\ShaderPostprocessor\ShaderPostprocessor.cs(72,52): error CS0122: 'VFXDataParticle.capacity' is inaccessible due to its protection level" 

I tried again with Unity 2019.4.16f and VFX Graph 7.5.2 and got 14 errors with 12 of them having to do with: 
Library\PackageCache\com.unity.collab-proxy@1.3.9\Editor\Models\Providers\Collab.cs(108,22): error CS1061

and this one error: Library\PackageCache\com.unity.collab-proxy@1.3.9\Editor\UserInterface\Bootstrap.cs(23,20): error CS0117: 'Collab' does not contain a definition for 'ShowChangesWindow'

in addition to the same one above. I successfully added FluvioFX from disk for both tries, but I have only been able to add the VFX graph from the Package Manager if that is the problem. I haven't found a copy of VFX graph to download and add from disk yet. Are there any other recommendations you have on getting this working?

**Comment by Anker13** [comment]
Hi there!
I have the same problem as @ o2co2. The problem is that the VFXParticle class (included in the UnityEditor.VFX package) has a class variable called "Capacity" that is declared protected. They try to access this variable in the "ShaderPostProcessor" script. I currently don't have a solution to this problem. But if someone can do something with this information, he or she may be able to help.
My system:
   - Unit 2019.4.9f1
   - Visual Effect Graph: vers. 7.3.1
   - FluvioFX
My error:
Unity-Project\fluviofx-master\Editor\ShaderPostprocessor\ShaderPostprocessor.cs(72,52): error CS0122: 'VFXDataParticle.capacity' is inaccessible due to its protection level

**Comment by melMass** [comment]
Amazing contribution @landonth !

**Comment by mjducharme** [comment]
@landonth it actually works with the newest Unity and VFX graph and HDRP on my system, I had to run the Fluvio installer again after replacing the code with your modified version.

However, there is something a bit odd with the behaviour it seems. When I run old Unity on my other computer and create a default Fluvio graph, it sorta looks like a water fountain by default. When I use the same settings with the newest version, for some reason those same defaults are causing the fountain to go into overdrive and the particles are flying away so fast and so far it no longer looks like a fountain with the defaults. I've compared the values between mine and the old version and they match. So something appears to have changed in the behaviour when the fixes were made.

**Comment by enginarer** [comment]
Hi, any update on the new release of the plugin? Or if we need to do the manual work to get fluviofx working on the recent version of Unity, can someone be kind to write a short documentation or checklist explaining what to do?

**Comment by AC0793** [comment]
I'm entering this comment to second both of @enginarer 's questions for Unity 2020.3. @lmontoute @neobits @landonth any new progress on fluviofx and documentation? Thanks.

**Comment by mjducharme** [comment]
@AC0793 @neobits if you want to use this now before my PR has been accepted, you can set the manifest.json dependencies to my own repo:

"com.fluvio.fx": "https://github.com/mjducharme/fluviofx.git"

**Comment by gabriverga** [comment]
hi, does it work for version 2021.2.10f1?

**Comment by mjducharme** [comment]
@gabriverga No, but I believe the only reason for this is that the cylinder seems to be deprecated in 2021, so the cylinder collider doesn't find it. You can probably get it to work for now by referencing the deprecated cylinder in the cylinder collider code until they remove it.

**Comment by gabriverga** [comment]
Thanks for the reply! Now on which version of unity is it working?

**Comment by gabriverga** [comment]
@mjducharme Thanks for the reply! now on which version of unity is it working?

**Comment by mjducharme** [comment]
@gabriverga I am running it on Unity 2020.3.28f1.

**Comment by mjducharme** [comment]
@gabriverga also keep in mind that you have to use my repo for the installation at the moment as this official one has not been updated yet: https://github.com/mjducharme/fluviofx

**Comment by gabriverga** [comment]
ok perfect, than I use this:

 "com.fluvio.fx": "https://github.com/mjducharme/fluviofx.git"

 on the manifest file, right?

**Comment by gabriverga** [comment]
@mjducharme @mjd ok perfect, than I use this:

 "com.fluvio.fx": "https://github.com/mjducharme/fluviofx.git"

 on the manifest file, right?

**Comment by mjducharme** [comment]
@gabriverga yes

**Comment by gabriverga** [comment]
@mjducharme I pressed on install and it gives me this error:

Packages\fluviofx-master\Editor\ShaderPostprocessor\ShaderPostprocessor.cs(72,52): error CS0122: 'VFXDataParticle.capacity' is inaccessible due to its protection level

**Comment by mjducharme** [comment]
@gabriverga Are you sure you don't have leftovers from the main fluvio install from the main repo? Another thing you can try is quit Unity and go back in after installing and run the install again, sometimes I find this is necessary.

**Comment by gabriverga** [comment]
@mjducharme yes I was wrong, now it seems to work. thank you so much!

**Comment by gabriverga** [comment]
@mjducharme where is it possible to see some of your works with FluvioFX?

**Comment by lmontoute** [comment]
Hey folks!

Other work has kept me quite busy so I haven't been able to take a good look at Fluvio for Unity version updates. Help is still wanted here - @mjducharme feel free to open a PR when you think this is ready to merge upstream and I'd be happy to review/accept it into the official repo!

**Comment by mjducharme** [comment]
@lmontoute I've submitted the pull request. My solution is probably not perfect, as there is most likely a way of preserving the "attributes." prefix as intended, but it works and behaves exactly the same as on 2019.2. It took me many, many hours to even get this working. My doctoral thesis project uses Fluvio, but I also needed 2020 LTS features, which necessitated me figuring out how to fix this.

**Comment by lmontoute** [comment]
Thanks! I'll take a look at #49 as soon as I can.

> My doctoral thesis project uses Fluvio

That's pretty rad. I would absolutely love to learn more about this whenever you are able!

**Comment by gabriverga** [comment]
Hi guys, do you know if it's possible to add some Keijiro assets in the same project with fluvioFX? because every time I go to add its lines of code in the manifest file it goes into error and fluviofx doesn't install correctly.

Can someone help me? Thanks

**Comment by mjducharme** [comment]
@gabriverga yes it is, but everytime I install something, I have to re-install fluvio again. Sometimes twice before it kicks in and works.

**Comment by gabriverga** [comment]
@mjducharme I have tried several times, always with the 2020.3.28f1 version with which I can install fluvioFX correctly but when I go to add the assets in the manifest script they are installed correctly and fluvio I cannot install it, I have tried several times to install (by tool - Install..) it but this comes out message:

FluvioFX install successful!
UnityEngine.Debug:Log (object)
FluvioFX.Editor.FluvioFXInstall:Install (bool) (at Packages/fluviofx-master/Install/FluvioFXInstall.cs:293)
FluvioFX.Editor.FluvioFXInstall:InstallFluvioFX () (at Packages/fluviofx-master/Install/FluvioFXInstall.cs:140)

Some scripts have compilation errors which may prevent obsolete API usages to get updated. Obsolete API updating will continue automatically after these errors get fixed.


and other 230 error

these are the assets i am trying to add if you want to try:

```
{
  "scopedRegistries": [
    {
      "name": "Keijiro",
      "url": "https://registry.npmjs.com",
      "scopes": [
        "jp.keijiro"
      ]
    }
  ],
  "dependencies": {
    "com.fluvio.fx": "https://github.com/mjducharme/fluviofx.git",
    "jp.keijiro.kino.post-processing": "2.1.15",
    "jp.keijiro.minis": "1.0.8",
    "jp.keijiro.vfx-extra": "1.0.0",
```

**Comment by mjducharme** [comment]
@gabriverga I don't have a lot of time to test this - my suspicion is that one of keijiro's packages is changing or overriding parts of the VFX Graph code also used by Fluvio. I am using a few packages by Keijiro successfully but none of the ones you list. Perhaps one of those is causing the issues - possibly "vfx-extra"?

**Comment by Nolram12345** [comment]
What about Unity 2020-2021 LTS compatibility ?

**Comment by gabriverga** [comment]
@lmontoute  Can't wait! fantastic. 
do you already know when it'll be ready?

**Comment by lmontoute** [comment]
Unfortunately I do not, but I think it'll be sooner rather than later. At the moment this project is pretty much worked on during my free time (my current clients do not have immediate use for the software).

**Comment by lmontoute** [comment]
> ah ok thanks! is it possible to see your portfolio or what do you do? (just curiosity) I've been using fluviofx for a few months now and it's great

Oh uh, sure! And also thank you!

I do work for a mid-size studio making all sorts of games and projects these days! I've also done quite a bit of consulting with Fluvio, from VFX and technical art to scientific research. For example, here's an interactive wall that I helped develop for Crayola: https://vimeo.com/170903339

More info on that project here:
https://www.binteractive.com/post/rainbow-rain

If you want, feel free to look me up on LinkedIn for more of my portfolio!

**Comment by Dante-LilyWhite** [comment]
Hi
I encountered the below issues. How can I fix this?
----------------
Library\PackageCache\com.fluvio.fx@ef71b9444e\Editor\Blocks\Collision\CollisionCylinder.cs(34,45): error CS0115: 'CollisionCone.includes': no suitable method found to override

same 7 error were occured
----------------

My environment is here
・Unity 2019.3.14
・VFX Graph 7.7.1

Best regards

**Comment by lilyvelour** [comment]
Just updating this to say that some progress is underway to support Unity 2022. It's been a bit delayed by health issues unfortunately, but I plan to get back to it within the coming weeks!

I'll also be looking at some mechanisms to more quickly support updates to the VFX graph (I'm a bit limited though since many methods remain internal and subject to change on Unity's end).

**Comment by loopervfx** [comment]
for what it's worth, this vfx graph feature for a custom hlsl block is about to hit 2023.2 (alpha) soon according to a unity dev: 
https://forum.unity.com/threads/visual-effect-graph-public-roadmap-now-live.884713/#post-8917499

the custom hlsl block roadmap item was also recently updated showing a screen capture of the feature in progress:
https://portal.productboard.com/unity/1-unity-platform-rendering-visual-effects/c/114-custom-hlsl-block

as lily mentioned, and as i understand: this is one of (but not all of the currently internal methods) required for fluviofx to be integrated within vfx graph. so, unity exposing this may be helpful in many ways for portability and limiting breaking changes with future unity versions, but i don't think we should expect it to be a "silver bullet" or "cure all", either.

it's also not clear if this unity 2023 feature will be backported to 2022. for now, we can only assume the custom hlsl block will only be for 2023 and newer as it's quite late to be adding features to 2022 right before it reaches the lts (long term support) release stream.
